### ISSUE TITLE
Questions about the code

### ISSUE THREAD

**Issue by eorroot** [mdyao/CSNorm#1]
Very nice work! 

![image](https://github.com/mdyao/CSNorm/assets/49010412/0c0dea1e-8005-40df-91fe-da453f739b0f)
What variable does (x) represent？

Have the authors tried in the object detection task?

**Comment by mdyao** [comment]
Thanks for your attention. 

Here (x) represents the feature normalized from the given feature x. We have corrected the code in the README.

In the current version of the paper, we have not yet attempted the object detection task. Nevertheless, we are keen to evaluate the performance of our CSNorm in various other computer vision tasks, which would be our future work. We are also pleased to see the versatile applicability of CSNorm, if anyone is interested in integrating it into their tasks.

Kindly note that one of the core steps of using CSNorm is to find the distinct component (e.g., lightness in our task), and design proper targets to drive the optimization of CSNorm.
