### ISSUE TITLE
Can it be applied to other fields as a general normalization method?

### ISSUE THREAD

**Issue by Breeze-Zero** [mdyao/CSNorm#3]
Thank you very much for your work. I would need some channel selective normalization on other tasks as well, but this training strategy might not be straightforward to apply. Is it possible to insert CSNorm without the training strategy mentioned in the paper?

**Comment by mdyao** [comment]
We are pleased to see the versatile applicability of CSNorm, if anyone is interested in integrating it into their tasks.

Kindly note that one of the core steps of using CSNorm is to find the distinct component (e.g., lightness in our task), and design proper targets to drive the optimization of CSNorm.
