### ISSUE TITLE
About DRBN+CSNorm

### ISSUE THREAD

**Issue by kravrolens** [mdyao/CSNorm#4]
Hi, Thanks for opening the source code. I am trying to understand it and want to ask a question:

Where is the CSNorm operation added to the DRBN network?

**Comment by mdyao** [comment]
Thanks for your attention. We add CSNorm in the middle part of the DRBN network. Also, you can try other positions, even applying multiple times. This opens up an exciting avenue for further exploration. Feel free to explore these possibilities.
