### ISSUE TITLE
Trained model

### ISSUE THREAD

**Issue by baolinv** [mdyao/CSNorm#5]
It's a very interesting work. Could you provide your trained model? Thanks a lot.

**Comment by zyz-code** [comment]
> It's a very interesting work. Could you provide your trained model? Thanks a lot.

它的代码是不是需要我们自己去找数据集训练测试，比如找到LOL数据集然后再添加到路径里？

**Comment by mdyao** [comment]
@baolinv Hi, now you can find the model in /models/ckpts/ and feel free to try it!
