### ISSUE TITLE
Frequency-based Perturbation 

### ISSUE THREAD

**Issue by baolinv** [mdyao/CSNorm#6]
I read your code and didn't find you use "perturb the lightness of the input image" step 2 in paper. 
Did I miss something?

**Comment by mdyao** [comment]
I regret to inform you that there was a mix-up in the initial code version where 'input' and 'input_aug' were mistakenly interchanged. However, I'm pleased to inform you that the code has now been rectified. The corrected code can be found in the 'CSNorm_model.py' file, specifically under the line 'self.img_pred = self.netG(self.img_input_aug, aug=True)'. This corresponds to what we described as 'step 2' in our paper. Please note that the only difference between this step and 'step 1' is that we have changed our input from 'img_input' to 'img_input_aug'.
