### ISSUE TITLE
Question on Table1.

### ISSUE THREAD

**Issue by dgjung0220** [mdyao/CSNorm#7]
I enjoyed reading your paper. 
However, I had difficulty understanding Table 1. 
I understood that the training data in Table 1 consists of original, interp, and scale. 
Are the evaluation data used in actual measurements the same for all three cases? 
I'm having trouble understanding why SSIM could be higher in the results trained with interp or scale.

**Comment by mdyao** [comment]
Hi, "original, interp, and scale" represent the test data rather than the training data. We only use the original dataset for training.

**Comment by dgjung0220** [comment]
Thank you, I understand.
