### ISSUE TITLE
About alternating training strategy

### ISSUE THREAD

**Issue by NB-Xie** [mdyao/CSNorm#8]
Hi, thank you for sharing the code!
I don't understand quite well about the alternating training strategy, 

In NAFNet.py, is it only one step?  sorry I dont understand it well
        ###################### init CSNorm ##################
        self.gate = Generate_gate()
        for i in range(512):
            setattr(self, 'CSN_' + str(i), nn.InstanceNorm2d(1, affine=True))
            freeze_direct(getattr(self, 'CSN_' + str(i)))
        freeze(self.gate)
        ###################### init CSNorm ##################

I am wondering if you would like to share more details about: 
how do you implement these 2 steps?

**Comment by mdyao** [comment]
Hi, the code you mentioned is the modification on the network architecture, where we add the CSNorm layer. The 2-step training strategy is in the trainer file (https://github.com/mdyao/CSNorm/blob/main/models/CSNorm_model.py).
